
const EErrors = {
    OPERATION_SUCCESSFUL: 0,
    DEFAULT: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    INVALID_PERMISSIONS_ERROR:4,
    MONGO_ERROR: 5,
    METHOD_NOT_IMPLEMENTED: 6,
    INVALID_VALUES: 7,
    TEST_ERROR: 8,
    MULTER_ERROR: 9,
    MONGO_ERROR: 10,
    UNDEFINED_ERROR: -1 
}
export default EErrors;